[project]
name = "fastmcp-demo"
version = "0.1.0"
description = "A minimal FastMCP server demo."
dependencies = [
    "fastmcp>=2.3.3",
    "requests>=2.31.0",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta" 
